version: 2.1

jobs:
  run-test-and-coverage:
    working_directory: ~/express-boilerplate
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Install JUnit coverage reporter
          command: npm install --save-dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npm run ci:test
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/test-results.xml"

      - run:
          name: Run Coverage
          command: npm run coverage

      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: reports/junit/test-results
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: reports/junit

      - run:
          name: Check coverage
          command: npm run ci:check-coverage
workflows:
  run-test-and-coverage:
    jobs:
      - run-test-and-coverage
